[package]
name = "adventofcode2021"
edition = '2021'
version = "1.0.0"
authors = ["liyuntao <liyuntao58607@gmail.com>"]

[dependencies]
chrono = "0.4.6"
lazy_static = "1.4.0"
#num-iter = "0.1"
regex = "1"
