[package]
name = "adventofcode2021"
edition = '2021'
version = "1.0.0"
authors = ["liyuntao <liyuntao58607@gmail.com>"]

[dependencies]
chrono = "0.4.6"
itertools = "0.10.2"
lazy_static = "1.4.0"
regex = "1"
